### ISSUE TITLE
Background hole looks broken in 3 World

### ISSUE THREAD

**Issue by P1tt187** [DigglesMods/DigglesHDmod#4]
![kristall](https://user-images.githubusercontent.com/1545867/102294820-5e783c80-3f4a-11eb-8bb9-de599b96806d.png)

**Comment by cech12** [comment]
This is not an issue of the HD mod. The game has problems to show the background correctly during the story. Please test to start a sandbox game in the third world. If all looks fine there, it is the game bug.

If you unistall the HD mod, the same issue is there in the original game with the original textures. :)
